# Site settings
title: Adam Paszke
# email: your-email@domain.com
description: >
  A blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://apaszke.github.io" # the base hostname & protocol for your site
twitter_username: apaszke
github_username:  apaszke

# Build settings
markdown: kramdown

# Output settings
permalink: none
