# Site settings
title: Chuan Wang
email:
description: "In me the tiger sniffs the rose."
baseurl: ""
url: "http://wangchuan.github.io"
github_username: wangchuan

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
    - html_toc
    - strikethrough
    - lax_spacing
    - footnotes
pygments: true
permalink: pretty